language: java
sudo: false
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn clean deploy --settings target/travis/settings.xml || mvn clean verify --settings target/travis/settings.xml"
 
dist: trusty

jdk:
  - openjdk11

# whitelist
branches:
  only:
    - master

env:
  global:
    - secure: "oQK6bpODrpvLzs/ljjfcffVYNCxFRCdhoN8/s5r6fHFkHVBA3HO8hDbilq0rwYimjPgP1X1gr+5tE2VfxkvYiagBxrbx3rkUomSEKIOT/2mR8xUTEzfB6Cen4sZqPw+FX+QfdGodR10aj+ND1BmpiQGRFV/D71GLhuCmNSGRMd6T7f4OHytgt3eTNK2Ra5AQI1DYdchKj/IdAmRAz6nn1RKsEUdsqEepXE9FH2FaAhqMr0gGr16mehnbFnUQ+0g+jnOI4299Wyhn5tvb4+io698iXGd/+iNXLw5u7wHiYqglEtVpTt2TUYgG5PTeDShyh5pc/5d6WOPQVcRrcxNFsH5Bl1UpB/fgUqpmkuec4n94phKumfBnCNYpm2dk1rCNrR+az6yeUCqXWgC5BOldLpaB2pwTUfGxG5FNJXNYA71IRMBK0i4ipfQFXZLetIiGoZhpPhDRsHJNhmdUE2Oazjsarfr6v+S92MX3tZeaAC+ZpnTGns1OcW7hMmSQ+PVKo6x9Kq3XxZkIMqmMyHC0/0p4h3rryDsqh2nUOD3TsmLZJs91ZVSQDgnK/JIH1sGV8Pvksw0QhKtx2b4yU43ManCAvHjoIy5rBONIxtGfsgtw6/cawA6n09Oe/FV8iAPoQY0WyI6FUV2Hke+6zq8sXe9le1XAJeMNWlIVWDce5iI="
    - secure: "fgV6H2wfVbONyuqr4nEge5zK4QBBjdlYIai2umWaNLyZ8gvRRkX8bvEjPM9yM4bN5j0b9CnPDdINQQ6Bh/uzt1FDSmlSReXgbY7eS02aR8Gvl69U+DIfEGGZRTLbrEkwlzqh60EMobZ9YH+QLHjTCAefG5lg2bPzkv/NNFHP2zeFYRbA/0XXXqn0McgBR6hkuvhItKc24rkTC4ukx6G/uZAHvI9nu+hfBlaAO2Joza2J4vIF2aR2OyHQOR5kLIj2fqFnms6rv8Zl/bG1YfhVzbm6HeuQlVAIVx3Kd5tsCn91xnLwOas7m/XTLpiKJUVfWwDRtVjXa8OTJozHbT67kURodNKdWIXdY/+jcsp1LQ9d+o3LYNGDGCPOFKbONo1rPS9fOmV9kC0RvKSKmo+QOk8hAY02QHNHbUG5BkkIJKUh7nMqwdjJwT6BO476kPcfSGR06X6CP+uIlaz448tbBNCyqKgsNLMM2CiFaoYiSRDPX2V+rnEJg5XI8buEBh60ivAS3P1nyA1LiMRUKP9XvbDFFpjjcbmf/A+UTuczBkSSWw8n3MX1mQ310uW3Rj+qmJAihP7PgTyIWR+nG+KnO6OUNIYsQQNAQKGo12b6m7tQhbEVBBrIlInar0RyTayVDXtV3YoOK27uHFnNLa0U3DorlmE174AucsRu0kJFyRE="